apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-db-pvc
  namespace: harbor
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs
